{% set name = "at-spi2-core" %}
{% set version = "2.36.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "88da57de0a7e3c60bc341a974a80fdba091612db3547c410d6deab039ca5c05a" %}

# Prior to conda-forge, Copyright 2014-2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('at-spi2-core', max_pin='x.x') }}
  missing_dso_whitelist:  # [linux]
    - "*/libX11.so*"  # [linux]
    - $RPATH/libc.so.6  # [linux]
  ignore_run_exports:
    - gettext

requirements:
  build:
    - meson
    - ninja
    - cmake  # [osx and arm64]
    - pkg-config
    - pthread-stubs  # [linux]
    - {{ compiler('c') }}
    # gobject-introspection 1.* requires setuptools at runtime, but
    # setuptools >= 65.0.0 is lacking the msvccompiler module in distutils.
    # https://github.com/pypa/setuptools/pull/3505
    - setuptools <65
    - python 3.11
    - gobject-introspection 1.*  # [not win]
  host:
    - dbus
    - gettext
    - glib
    - gobject-introspection
    - python
    - xorg-libx11  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxtst  # [linux]
    - xorg-xorgproto  # [linux]
  run:
    - dbus
    - gettext
    - glib
    - gobject-introspection

test:
  commands:
    - test -f $PREFIX/include/at-spi-2.0/atspi/atspi.h  # [unix]
    - test -f $PREFIX/lib/libatspi${SHLIB_EXT}  # [unix]

about:
  home: http://www.gtk.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: D-Bus-based implementation of AT-SPI accessibility framework
  description: |
    This package includes the protocol definitions for the new D-Bus at-spi.

    Also included is the daemon necessary for forwarding device events and
    registering accessible applicaitions.
  dev_url: https://gitlab.gnome.org/GNOME/at-spi2-core

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
    - katietz